version: "3.8"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - EMAILADDRESS=${EMAILADDRESS}
      - EMAILPASSWORD=${EMAILPASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - /FG-Academy-BE/public:/app/public
    expose:
      - 8080
    depends_on:
      - mysql
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    depends_on:
      - app
    expose:
      - 3000
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./FG-Academy-BE/public:/var/www/html
      - ./FG-Academy-BE/log/directory:/var/log/nginx
    depends_on:
      - frontend
      - app
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  mysql-data:
