version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=Rhcehdtksdkzkepal*
      - MYSQL_DATABASE=fgacademydb
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=Rhcehdtksdkzkepal*
      - DB_NAME=fgacademydb
      - EMAILADDRESS=rkdckdfyyd@naver.com
      - EMAILPASSWORD=spdlqjwhgdk3*
      - JWT_SECRET=0dd8d1d7c673300e0e800e10e13eb6ee1414c140e046ebf7e2229010ab7ab79a10f06fddeebabfb428b6a380aa12654c
    volumes:
      - /FG-Academy-BE/public:/app/public
    depends_on:
      - mysql
    restart: always

volumes:
  mysql-data:
